/*
 * generated by Xtext 2.29.0
 */
package DSLQNAME;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.xtext.resource.IResourceServiceProvider;
import org.eclipse.xtext.resource.XtextResourceSet;
import org.eclipse.xtext.util.DisposableRegistry;
import org.eclipse.xtext.web.server.InvalidRequestException;
import org.eclipse.xtext.web.servlet.XtextServlet;

import com.google.gson.Gson;
import com.google.inject.Injector;

/**
 * Deploy this class into a servlet container to enable DSL-specific services.
 */
@WebServlet(name = "XtextServices", urlPatterns = "/xtext-service/*")
public class DSLNAMEServlet extends XtextServlet {

    private static final long serialVersionUID = 1L;

    DisposableRegistry disposableRegistry;

    public void init() throws ServletException {
        super.init();
        Injector injector = new DSLNAMEWebSetup().createInjectorAndDoEMFRegistration();
        this.disposableRegistry = injector.getInstance(DisposableRegistry.class);
    }

    private class Response {
        public String output;
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String serviceID = req.getPathInfo().substring(1);
        if ("to-xmi".equals(serviceID)) {
            String sResult = exportXMI(req);

            if (sResult != "") {
                resp.setStatus(200);
                resp.setContentType("application/json");
                
                Response r = new Response();
                r.output = sResult;
                
                PrintWriter pw = resp.getWriter();

                pw.print(new Gson().toJson(r));

                pw.close();
            } else {
                resp.setStatus(500);
            }
        } else {
            super.doPost(req, resp);
        }
    }

    private class RequestStructure {
        public String input;
    }

    private String exportXMI(HttpServletRequest req) throws InvalidRequestException.UnknownLanguageException, IOException {
        StringBuffer jb = new StringBuffer();
        String line = null;
        BufferedReader reader = req.getReader();
        while ((line = reader.readLine()) != null)
            jb.append(line);

        RequestStructure reqObj = new Gson().fromJson(jb.toString(), RequestStructure.class);		
        
        URI emfURI = URI.createURI("input.LANGUAGE_EXT");
        IResourceServiceProvider resourceServiceProvider = IResourceServiceProvider.Registry.INSTANCE.getResourceServiceProvider(emfURI);
        if (resourceServiceProvider == null) {
            throw new InvalidRequestException.UnknownLanguageException ("Unable to identify the Xtext language.");
        }
		
        Injector injector = resourceServiceProvider.get(Injector.class);

        XtextResourceSet resourceSet = injector.getInstance(XtextResourceSet.class);

        Resource xtextResource = resourceSet.createResource(emfURI);
        xtextResource.load(new ByteArrayInputStream(reqObj.input.getBytes()), null);
        EcoreUtil.resolveAll(xtextResource);

        Resource xmiResource = resourceSet.createResource(URI.createFileURI("result.xmi"));
        xmiResource.getContents().add(xtextResource.getContents().get(0));
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            xmiResource.save(baos, null);
            return baos.toString();
        } catch (IOException e) {
            e.printStackTrace();
        }

        return "";
	}

    public void destroy() {
        if (disposableRegistry != null) {
            disposableRegistry.dispose();
            disposableRegistry = null;
        }
        super.destroy();
    }
}
