name: run-unit-tests

on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
 
permissions:
  contents: read
  actions: read
  
jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
                        
      - name: Setup node 18
        uses: actions/setup-node@v4
        with: 
          node-version: 18
          
      - name: Install node dependencies
        working-directory: ./xtext/editorserver
        run: npm ci
      
      - name: Code linting - Xtext Editor Server
        working-directory: ./xtext/editorserver
        run: npm run lint

      - name: Upload Lint Results - Xtext Editor Server
        uses: actions/upload-artifact@v4  
        if: ${{ !cancelled() }}           # run this step even if previous step failed
        with:
          name: lint-results-editor-server
          path: |
            ./xtext/editorserver/reports/lint-results.xml

      - name: Run the unit tests
        id: run-unit-tests
        working-directory: ./xtext/editorserver
        if: success() || failure() && steps.build-xtext-es.outcome == 'success'
        run: npm run coverage

      - name: Upload Test Results - Xtext Editor Server
        uses: actions/upload-artifact@v4  
        if: success() || failure() && steps.run-unit-tests.outcome == 'success'
        with:
          name: test-results-editor-server
          path: '**/reports/TESTS*.xml'

      - name: Setup .NET Core - for coverage report # Required to execute ReportGenerator
        uses: actions/setup-dotnet@v4
        if: success() || failure() && steps.run-unit-tests.outcome == 'success'
        with:
            dotnet-version: 8.x
            dotnet-quality: 'ga'

      - name: Create coverage md report 
        uses: danielpalme/ReportGenerator-GitHub-Action@5.5.0
        if: success() || failure() && steps.run-unit-tests.outcome == 'success'
        with:
            reports: '**/reports/coverage/*.xml'
            targetdir: ./reports/
            reporttypes: MarkdownSummaryGithub
    
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4  
        if: ${{ !cancelled() }}           # run this step even if previous step failed
        with:
          name: coverage-results-editor-server
          path: "./reports/SummaryGithub.md"

